# Generated by Django 5.0.1 on 2024-01-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_bio_alter_user_family_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='family_name',
        ),
    ]
